# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text1',
            field=models.TextField(default=datetime.datetime(2018, 7, 11, 16, 57, 19, 393000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
