# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text3',
            field=models.TextField(default='teste2'),
            preserve_default=False,
        ),
    ]
