# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-12 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_text3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text4',
            field=models.TextField(default='teste 2'),
            preserve_default=False,
        ),
    ]
