# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-16 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_text4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text4',
            new_name='texto4',
        ),
    ]
