# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180727_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='alu_curso',
            field=models.CharField(max_length=200),
        ),
    ]
