# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180801_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sats_cpf', models.CharField(max_length=11)),
                ('sats_check', models.CharField(max_length=2)),
                ('sats_quest_01', models.CharField(max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
