# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-27 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180827_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_cpf', models.CharField(max_length=11)),
                ('pro_check', models.CharField(max_length=10)),
                ('pro_gender', models.CharField(choices=[('rb1', '1'), ('rb2', '2'), ('rb3', '3'), ('rb4', '4'), ('rb5', '5'), ('rb6', '6'), ('rb7', '7'), ('rb8', '8'), ('rb9', '9'), ('rb10', '10')], max_length=20)),
            ],
        ),
    ]
