# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-31 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuso',
            new_name='Curso',
        ),
    ]
