# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180831_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='alu_status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
