# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-31 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_sala_sala_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='conecta',
            name='con_curso',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
