# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-31 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_conecta_con_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='bol_cpf',
            field=models.CharField(default='38019987894', max_length=11),
            preserve_default=False,
        ),
    ]
