# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_boleto_bol_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_sala',
            field=models.CharField(default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status_ajuste',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_boleto',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_bolsa',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_card',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_rematricula',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_status',
            field=models.CharField(max_length=2),
        ),
    ]
