# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-13 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180904_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=130)),
                ('text2', models.CharField(max_length=130)),
                ('text3', models.CharField(max_length=130)),
                ('text4', models.CharField(max_length=130)),
                ('text5', models.CharField(max_length=130)),
                ('text6', models.CharField(max_length=130)),
                ('text7', models.CharField(max_length=130)),
                ('text8', models.CharField(max_length=130)),
                ('text9', models.CharField(max_length=130)),
                ('text10', models.CharField(max_length=130)),
            ],
        ),
    ]
