# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-13 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20180913_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomodal',
            name='text11',
        ),
        migrations.RemoveField(
            model_name='infomodal',
            name='title11',
        ),
    ]
