# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180913_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='alu_id_cur',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='cur_id_cur',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
