# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-08 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_sats_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_curso', models.CharField(max_length=2)),
                ('pro_disciplina', models.CharField(max_length=150)),
                ('pro_avaliacao', models.CharField(max_length=30)),
                ('pro_professor', models.CharField(max_length=30)),
                ('pro_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_serie', models.CharField(max_length=20)),
            ],
        ),
    ]
