# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-08 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_provas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provas',
            name='pro_data',
        ),
    ]
