# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_provas_pro_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='provas',
            name='pro_data',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provas',
            name='pro_serie',
            field=models.CharField(max_length=30),
        ),
    ]
